"""rename department

Revision ID: 44f510a1d0c9
Revises: 1a1415b6cd97
Create Date: 2025-03-26 04:43:19.645327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f510a1d0c9'
down_revision = '1a1415b6cd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
